apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-terminal
  labels:
    app: web-terminal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-terminal
  template:
    metadata:
      labels:
        app: web-terminal
    spec:
      serviceAccountName: web-terminal
      containers:
      - name: web-terminal
        image: kube-web-terminal:v0.1
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: web-terminal
spec:
  type: NodePort
  selector:
    app: web-terminal
  ports:
    - protocol: TCP
      port: 8081
