apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-terminal
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: web-terminal
rules:
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: web-terminal
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: web-terminal
subjects:
  - kind: ServiceAccount
    name: web-terminal
    namespace: default